# -*- coding: utf-8 -*-
"""BSP GRU Layers Model Fitter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTe5SPfu4QPOwqr0hZaiO0j33FWXbbG1
"""

# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import GRU, Dropout, Dense
from keras.callbacks import EarlyStopping
import time
import os

def init_data():
    CSV_FILE = "atakanka350@gmail.com.csv"  # Make sure this is uploaded to Colab
    CSV_METADATA_SKIP = 25
    TIME_COL = "Zaman damgası (GG-AA-YYYY/ss:dd:sn)"
    GLUCOSE_COL = "Glikoz Değeri (mg/dL)"
    SEQ_LEN = 12

    df_raw = pd.read_csv(CSV_FILE, sep=";")
    
    # Replace categorical glucose values
    df_raw.iloc[CSV_METADATA_SKIP:, 7] = df_raw.iloc[CSV_METADATA_SKIP:, 7].replace({"Yüksek": 400, "Düşük": 40})
    df_raw[GLUCOSE_COL] = pd.to_numeric(df_raw[GLUCOSE_COL], errors="coerce")
    
    # Convert datetime and extract time-of-day
    df_raw[TIME_COL] = pd.to_datetime(df_raw[TIME_COL], errors='coerce')
    df_raw["hour"] = df_raw[TIME_COL].dt.hour
    df_raw["minute"] = df_raw[TIME_COL].dt.minute
    df_raw["sin_time"] = np.sin(2 * np.pi * (df_raw["hour"] * 60 + df_raw["minute"]) / 1440)
    df_raw["cos_time"] = np.cos(2 * np.pi * (df_raw["hour"] * 60 + df_raw["minute"]) / 1440)
    
    # Drop rows with missing values
    df_clean = df_raw.dropna(subset=[GLUCOSE_COL, "sin_time", "cos_time"]).iloc[CSV_METADATA_SKIP:]
    
    # Feature scaling
    sc_glucose = MinMaxScaler()
    sc_time = MinMaxScaler()
    glucose_scaled = sc_glucose.fit_transform(df_clean[[GLUCOSE_COL]])
    sin_scaled = sc_time.fit_transform(df_clean[["sin_time"]])
    cos_scaled = sc_time.fit_transform(df_clean[["cos_time"]])
    
    # Combine features: [glucose, sin_time, cos_time]
    data = np.hstack((glucose_scaled, sin_scaled, cos_scaled))
    
    # Create sequences (from the entire dataset first)
    def create_sequences(data_array, seq_length):
        X, y = [], []
        for i in range(seq_length, len(data_array)):
            X.append(data_array[i-seq_length:i])  # shape: (SEQ_LEN, 3)
            y.append(data_array[i, 0])  # predict glucose only
        return np.array(X), np.array(y)
    # Generate sequences for the entire dataset
    X_sequences_all, y_sequences_all = create_sequences(data, SEQ_LEN)
    
    return X_sequences_all, y_sequences_all, sc_glucose


from multiprocessing import Pool, cpu_count


def train_gru_model(num_of_layers):
    print(f"Starting model with {num_of_layers} layers on PID {os.getpid()} at {time.strftime('%X')}", flush=True)

    EPOCHS = 50
    BATCH_SIZE = 24
    DROPOUT = 0.2
    
    # Define split percentages (adjust as needed)
    TEST_SPLIT_RATIO = 0.1  # e.g., 15% of data for final testing
    VAL_SPLIT_RATIO = 0.1   # e.g., 15% of *training data* for validation
    
    
    X_sequences_all, y_sequences_all, sc_glucose = init_data()
    
    # 1. Split into Training+Validation set and Test set (preserving temporal order)
    test_size = int(len(X_sequences_all) * TEST_SPLIT_RATIO)
    X_train_val = X_sequences_all[:-test_size]
    y_train_val = y_sequences_all[:-test_size]
    X_test = X_sequences_all[-test_size:]
    y_test = y_sequences_all[-test_size:]
    
    # 2. Split Training+Validation set into Training set and Validation set (preserving temporal order)
    val_size = int(len(X_train_val) * VAL_SPLIT_RATIO)
    X_train = X_train_val[:-val_size]
    y_train = y_train_val[:-val_size]
    X_val = X_train_val[-val_size:]
    y_val = y_train_val[-val_size:]
    
    # Build GRU model
    model = Sequential()
    model.add(GRU(units=50, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
    model.add(Dropout(DROPOUT))
    for _ in range(num_of_layers):  # Deep LSTM as in your original code
        model.add(GRU(units=50, return_sequences=True))
        model.add(Dropout(DROPOUT))
    model.add(GRU(units=50))  # Final LSTM without return_sequences
    model.add(Dropout(DROPOUT))
    model.add(Dense(units=1))  # Output: 1 glucose prediction
    
    early_stopping = EarlyStopping(
        monitor='val_loss',     # Monitor validation loss
        patience=10,            # Stop if val_loss doesn't improve for 10 epochs
        restore_best_weights=True # Restore model weights from the epoch with the best val_loss
    )
    
    # Compile and train
    model.compile(optimizer="adam", loss="mean_squared_error")
    model.fit(X_train,
              y_train,
              epochs=EPOCHS,
              batch_size=BATCH_SIZE,
              validation_data=(X_val, y_val), # Use the validation set here
              callbacks=[early_stopping],     # Add the callback here
              verbose=0)
    
    # Evaluate the model on the TEST set (this is the true generalization performance)
    predicted_glucose_scaled = model.predict(X_test)
    predicted_glucose = sc_glucose.inverse_transform(predicted_glucose_scaled)
    
    # Get true values for comparison from the y_test
    true_glucose = sc_glucose.inverse_transform(y_test.reshape(-1, 1))
    
    ''' plt.figure(figsize=(12, 6))
    plt.plot(true_glucose, color='red', label=f'Real Blood Sugar{i}')
    plt.plot(predicted_glucose, color='blue', label='Predicted Blood Sugar')
    plt.title('Blood Sugar Prediction with Time-of-Day Features')
    plt.xlabel('Time Step')
    plt.ylabel('Blood Sugar (mg/dL)')
    plt.legend()
    plt.grid(True)
    plt.show() '''
    
    def accuracy_finder(predicted, real, percentage_error_threshold=0.03, absolute_threshold=5):
        absolute_error = np.abs(predicted - real)
        percentage_error = np.abs((predicted - real) / real)
    
        within_percentage = np.sum(percentage_error <= percentage_error_threshold)
        within_absolute = np.sum(absolute_error <= absolute_threshold)
    
        percent_accuracy = (within_percentage / len(real)) * 100
        absolute_accuracy = (within_absolute / len(real)) * 100
    
        print(f"✅ Accurate Predictions within {percentage_error_threshold * 100:.1f}%: {percent_accuracy:.2f}%")
        print(f"✅ Accurate Predictions within ±{absolute_threshold} mg/dL: {absolute_accuracy:.2f}%")
        return percent_accuracy, absolute_accuracy
    
    print(f"🛑 Early stopped at epoch: {early_stopping.stopped_epoch}")
    print(f"🔙 Best epoch (restored): {early_stopping.best_epoch}")
    print("NUMBER OF LAYERS NOW:", num_of_layers)

    # Evaluate
    percen, absol = accuracy_finder(predicted_glucose, true_glucose)
    return num_of_layers, percen, absol


# 🔐 This is critical to prevent freeze
if __name__ == "__main__":
    with Pool(8) as pool:
        results = pool.map(train_gru_model, range(20))